export type ProjectStatus = "Active" | "Completed" | "On hold" | "Draft";
export type ProjectCategory = "Residential" | "Commercial" | "Both" | "Shed";

export interface PreviewProject {
  id: string;
  code: string;
  name: string;
  location: string | null;
  organization: string;
  category: ProjectCategory;
  status: ProjectStatus;
  progress: number | null;
  unitsSold: number | null;
  unitsTotal: number | null;
  updatedLabel: string;
  updatedMinutesAgo: number;
}

export const previewProjects: PreviewProject[] = [
  {
    id: "project-001",
    code: "PRJ-00042",
    name: "Riverstone Residency",
    location: "Ahmedabad, Gujarat",
    organization: "Arora Builders",
    category: "Residential",
    status: "Active",
    progress: 62,
    unitsSold: 44,
    unitsTotal: 80,
    updatedLabel: "18 minutes ago",
    updatedMinutesAgo: 18,
  },
  {
    id: "project-002",
    code: "PRJ-00057",
    name: "Green Acres Commercial Centre",
    location: "Bopal, Ahmedabad",
    organization: "Arora Builders",
    category: "Commercial",
    status: "On hold",
    progress: 38,
    unitsSold: 12,
    unitsTotal: 28,
    updatedLabel: "2 hours ago",
    updatedMinutesAgo: 120,
  },
  {
    id: "project-003",
    code: "PRJ-00061",
    name: "Aarohi Heights",
    location: "Gota, Ahmedabad",
    organization: "Mehta Realty",
    category: "Residential",
    status: "Active",
    progress: 81,
    unitsSold: 66,
    unitsTotal: 72,
    updatedLabel: "Today, 10:32",
    updatedMinutesAgo: 204,
  },
  {
    id: "project-004",
    code: "PRJ-00065",
    name: "Westline Industrial Shed",
    location: "Sanand, Gujarat",
    organization: "Arora Builders",
    category: "Shed",
    status: "Active",
    progress: 27,
    unitsSold: null,
    unitsTotal: null,
    updatedLabel: "Today, 09:14",
    updatedMinutesAgo: 282,
  },
  {
    id: "project-005",
    code: "PRJ-00071",
    name: "શિવમ રેસિડેન્સી – Phase 2",
    location: "Chandkheda, Ahmedabad",
    organization: "Shivam Buildcon",
    category: "Residential",
    status: "Draft",
    progress: 0,
    unitsSold: 0,
    unitsTotal: 96,
    updatedLabel: "Yesterday",
    updatedMinutesAgo: 1_450,
  },
  {
    id: "project-006",
    code: "PRJ-00076",
    name: "Harbour View Business Park – Block A and Block B",
    location: "Surat, Gujarat",
    organization: "Meridian Estates",
    category: "Commercial",
    status: "Active",
    progress: 54,
    unitsSold: 23,
    unitsTotal: 48,
    updatedLabel: "Yesterday",
    updatedMinutesAgo: 1_720,
  },
  {
    id: "project-007",
    code: "PRJ-00080",
    name: "Lotus Courtyard",
    location: "Vadodara, Gujarat",
    organization: "Mehta Realty",
    category: "Both",
    status: "Completed",
    progress: 100,
    unitsSold: 118,
    unitsTotal: 118,
    updatedLabel: "2 days ago",
    updatedMinutesAgo: 2_880,
  },
  {
    id: "project-008",
    code: "PRJ-00083",
    name: "Nirman Logistics Yard",
    location: null,
    organization: "Arora Builders",
    category: "Shed",
    status: "Draft",
    progress: null,
    unitsSold: null,
    unitsTotal: null,
    updatedLabel: "3 days ago",
    updatedMinutesAgo: 4_320,
  },
  {
    id: "project-009",
    code: "PRJ-00089",
    name: "Lakefront One",
    location: "Thaltej, Ahmedabad",
    organization: "Northstar Habitat",
    category: "Both",
    status: "Active",
    progress: 73,
    unitsSold: 52,
    unitsTotal: 64,
    updatedLabel: "3 days ago",
    updatedMinutesAgo: 4_640,
  },
  {
    id: "project-010",
    code: "PRJ-00094",
    name: "Orchid Retail Arcade",
    location: "Rajkot, Gujarat",
    organization: "Meridian Estates",
    category: "Commercial",
    status: "On hold",
    progress: 46,
    unitsSold: 14,
    unitsTotal: 36,
    updatedLabel: "4 days ago",
    updatedMinutesAgo: 5_760,
  },
  {
    id: "project-011",
    code: "PRJ-00102",
    name: "Saffron Enclave",
    location: "Nikol, Ahmedabad",
    organization: "Shivam Buildcon",
    category: "Residential",
    status: "Active",
    progress: 19,
    unitsSold: 9,
    unitsTotal: 84,
    updatedLabel: "5 days ago",
    updatedMinutesAgo: 7_200,
  },
  {
    id: "project-012",
    code: "PRJ-00108",
    name: "Central Foundry Redevelopment",
    location: "Naroda, Ahmedabad",
    organization: "Arora Builders",
    category: "Commercial",
    status: "Draft",
    progress: 0,
    unitsSold: 0,
    unitsTotal: 22,
    updatedLabel: "6 days ago",
    updatedMinutesAgo: 8_640,
  },
  {
    id: "project-013",
    code: "PRJ-00111",
    name: "Sunfield Villas",
    location: "Anand, Gujarat",
    organization: "Northstar Habitat",
    category: "Residential",
    status: "Completed",
    progress: 100,
    unitsSold: 34,
    unitsTotal: 34,
    updatedLabel: "8 days ago",
    updatedMinutesAgo: 11_520,
  },
  {
    id: "project-014",
    code: "PRJ-00116",
    name: "Cedar Square",
    location: "Vastrapur, Ahmedabad",
    organization: "Mehta Realty",
    category: "Commercial",
    status: "Active",
    progress: 67,
    unitsSold: 31,
    unitsTotal: 42,
    updatedLabel: "9 days ago",
    updatedMinutesAgo: 12_960,
  },
  {
    id: "project-015",
    code: "PRJ-00120",
    name: "Aangan Affordable Housing Initiative",
    location: "Gandhinagar, Gujarat",
    organization: "Public Works Collective",
    category: "Residential",
    status: "Active",
    progress: 42,
    unitsSold: 88,
    unitsTotal: 240,
    updatedLabel: "11 days ago",
    updatedMinutesAgo: 15_840,
  },
  {
    id: "project-016",
    code: "PRJ-00126",
    name: "Eastern Freight Shed 04",
    location: "Changodar, Gujarat",
    organization: "Meridian Estates",
    category: "Shed",
    status: "Completed",
    progress: 100,
    unitsSold: null,
    unitsTotal: null,
    updatedLabel: "12 days ago",
    updatedMinutesAgo: 17_280,
  },
  {
    id: "project-017",
    code: "PRJ-00131",
    name: "Parkside Residences",
    location: "Satellite, Ahmedabad",
    organization: "Arora Builders",
    category: "Residential",
    status: "On hold",
    progress: 58,
    unitsSold: 40,
    unitsTotal: 76,
    updatedLabel: "14 days ago",
    updatedMinutesAgo: 20_160,
  },
  {
    id: "project-018",
    code: "PRJ-00134",
    name: "The Workshop Collective",
    location: "Makarba, Ahmedabad",
    organization: "Northstar Habitat",
    category: "Both",
    status: "Active",
    progress: 33,
    unitsSold: 7,
    unitsTotal: 18,
    updatedLabel: "15 days ago",
    updatedMinutesAgo: 21_600,
  },
  {
    id: "project-019",
    code: "PRJ-00139",
    name: "Crescent Business House",
    location: "Prahlad Nagar, Ahmedabad",
    organization: "Mehta Realty",
    category: "Commercial",
    status: "Draft",
    progress: null,
    unitsSold: null,
    unitsTotal: 30,
    updatedLabel: "18 days ago",
    updatedMinutesAgo: 25_920,
  },
  {
    id: "project-020",
    code: "PRJ-00144",
    name: "Umiya Industrial Campus",
    location: "Vatva, Ahmedabad",
    organization: "Shivam Buildcon",
    category: "Shed",
    status: "Active",
    progress: 12,
    unitsSold: null,
    unitsTotal: null,
    updatedLabel: "20 days ago",
    updatedMinutesAgo: 28_800,
  },
  {
    id: "project-021",
    code: "PRJ-00148",
    name: "Prerna Habitat",
    location: "Koba, Gandhinagar",
    organization: "Public Works Collective",
    category: "Residential",
    status: "Completed",
    progress: 100,
    unitsSold: 156,
    unitsTotal: 156,
    updatedLabel: "23 days ago",
    updatedMinutesAgo: 33_120,
  },
  {
    id: "project-022",
    code: "PRJ-00153",
    name: "Northbank Mixed-Use Quarter",
    location: "Motera, Ahmedabad",
    organization: "Northstar Habitat",
    category: "Both",
    status: "Active",
    progress: 49,
    unitsSold: 61,
    unitsTotal: 110,
    updatedLabel: "25 days ago",
    updatedMinutesAgo: 36_000,
  },
  {
    id: "project-023",
    code: "PRJ-00159",
    name: "Monarch Corporate Annex",
    location: "SG Highway, Ahmedabad",
    organization: "Meridian Estates",
    category: "Commercial",
    status: "On hold",
    progress: 71,
    unitsSold: 19,
    unitsTotal: 26,
    updatedLabel: "28 days ago",
    updatedMinutesAgo: 40_320,
  },
  {
    id: "project-024",
    code: "PRJ-00163",
    name: "Aster Homes",
    location: "Shela, Ahmedabad",
    organization: "Arora Builders",
    category: "Residential",
    status: "Draft",
    progress: 0,
    unitsSold: 0,
    unitsTotal: 54,
    updatedLabel: "30 days ago",
    updatedMinutesAgo: 43_200,
  },
];

export const statusOptions = [
  { value: "all", label: "All statuses" },
  { value: "Active", label: "Active" },
  { value: "Completed", label: "Completed" },
  { value: "On hold", label: "On hold" },
  { value: "Draft", label: "Draft" },
];

export const categoryOptions = [
  { value: "all", label: "All categories" },
  { value: "Residential", label: "Residential" },
  { value: "Commercial", label: "Commercial" },
  { value: "Both", label: "Both" },
  { value: "Shed", label: "Shed" },
];

