import { router, useLocalSearchParams } from 'expo-router';
import { useCallback, useEffect, useState } from 'react';
import { StyleSheet, View } from 'react-native';
import { useTranslation } from 'react-i18next';

import { AppIcon, AppText, Button, Card, CompactScreenHeader, EmptyState, IconButton, LoadingState, NirmanScreenBackground, StatusBadge } from '../../components/ui';
import { formatDate, formatInr, getLocalizedErrorMessage } from '../../i18n';
import { getActiveProject, getActiveProjectPermissions } from '../../lib/auth';
import { useLocalization, useSession } from '../../providers';
import { mobileText, mobileTheme } from '../../theme';
import { CustomerTabBar } from '../home/components';
import { KharchiAdjustmentSheet } from './kharchi-adjustment-sheet';
import { fetchKharchiDetail } from './services';
import type { KharchiAdvanceDetail } from './types';

const dateOnly = (value: string) => new Date(`${value}T12:00:00`);
export function KharchiDetailScreen() {
  const { kharchiId } = useLocalSearchParams<{ kharchiId?: string }>();
  const { t } = useTranslation('kharchi'); const { language } = useLocalization(); const { session } = useSession();
  const project = getActiveProject(session); const permissions = getActiveProjectPermissions(session);
  const organizationId = session?.activeOrganization?.id; const projectId = project?.id; const accessToken = session?.accessToken;
  const canAdjust = permissions.includes('kharchi:adjust') && project?.status === 'ACTIVE';
  const [detail, setDetail] = useState<KharchiAdvanceDetail | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [adjustOpen, setAdjustOpen] = useState(false);
  const load = useCallback(async () => { if (!kharchiId || !organizationId || !projectId || !accessToken) { setLoading(false); return; } setLoading(true); setError(''); try { setDetail(await fetchKharchiDetail(organizationId, projectId, kharchiId, accessToken)); } catch (loadError) { setError(getLocalizedErrorMessage(loadError, t('errors.detailFailed'))); } finally { setLoading(false); } }, [accessToken, kharchiId, organizationId, projectId, t]);
  useEffect(() => { void load(); }, [load]);
  return <NirmanScreenBackground footer={<CustomerTabBar activeKey="kharchi" />}>
    <CompactScreenHeader leading={<IconButton accessibilityLabel={t('actions.back')} icon="arrow-left" variant="glass" onPress={() => router.back()} />} title={t('detail.title')} subtitle={detail?.workerName ?? project?.name} action={canAdjust && detail ? <Button label={t('adjustment.shortAction')} size="sm" fullWidth={false} onPress={() => setAdjustOpen(true)} /> : undefined} />
    {loading ? <LoadingState label={t('loading.detail')} /> : error ? <EmptyState title={t('errors.title')} description={error} actionLabel={t('actions.retry')} onAction={() => void load()} /> : !detail ? <EmptyState title={t('detail.notFound')} description={t('detail.notFoundDescription')} /> : <>
      <Card style={styles.identity}><View style={styles.identityTop}><View style={styles.identityCopy}><AppText style={styles.code} weight={700}>{detail.workerCode} · {detail.trade}</AppText><AppText style={styles.worker} weight={700}>{detail.workerName}</AppText></View><StatusBadge label={t(`status.${detail.status}`)} tone={detail.status === 'DEDUCTED' ? 'success' : detail.status === 'PARTIALLY_DEDUCTED' ? 'info' : 'warning'} /></View><AppText style={styles.muted}>{formatDate(dateOnly(detail.requestDate), language)} · {t(`paymentMethod.${detail.paymentMethod}`)}</AppText></Card>
      <Card style={styles.card}><AppText style={styles.sectionTitle} weight={700}>{t('detail.amounts')}</AppText><Amount label={t('detail.original')} value={formatInr(Number(detail.amount), language)} /><Amount label={t('summary.adjustments')} value={formatInr(Number(detail.adjustmentAmount), language)} /><Amount label={t('detail.effective')} value={formatInr(Number(detail.effectiveAmount), language)} /><Amount label={t('summary.deducted')} value={formatInr(Number(detail.deductedAmount), language)} /><Amount label={t('summary.outstanding')} value={formatInr(Number(detail.outstandingAmount), language)} emphasis /></Card>
      {(detail.paymentReference || detail.notes) ? <Card style={styles.card}><AppText style={styles.sectionTitle} weight={700}>{t('detail.payment')}</AppText>{detail.paymentReference ? <DetailLine label={t('detail.reference')} value={detail.paymentReference} /> : null}{detail.notes ? <DetailLine label={t('detail.notes')} value={detail.notes} /> : null}<DetailLine label={t('detail.recordedAt')} value={formatDate(detail.paidAt, language, { dateStyle: 'medium', timeStyle: 'short', timeZone: 'Asia/Kolkata' })} /></Card> : null}
      <View style={styles.section}><AppText style={styles.sectionTitle} weight={700}>{t('detail.adjustments')}</AppText>{detail.adjustments.length ? detail.adjustments.map((item) => <Card key={item.id} style={styles.historyCard}><View style={styles.historyTop}><AppText weight={700}>{Number(item.amount) >= 0 ? t('detail.increase') : t('detail.decrease')}</AppText><AppText style={Number(item.amount) >= 0 ? styles.positive : styles.negative} weight={700}>{formatInr(Number(item.amount), language)}</AppText></View><AppText>{item.reason}</AppText><AppText style={styles.muted}>{formatDate(item.recordedAt, language, { dateStyle: 'medium', timeStyle: 'short', timeZone: 'Asia/Kolkata' })}</AppText></Card>) : <EmptyState title={t('detail.noAdjustments')} description={t('detail.noAdjustmentsDescription')} />}</View>
      <View style={styles.section}><AppText style={styles.sectionTitle} weight={700}>{t('detail.deductions')}</AppText>{detail.deductionAllocations.length ? detail.deductionAllocations.map((item) => <Card key={item.id} style={styles.historyCard}><View style={styles.historyTop}><View style={styles.deductionLabel}><AppIcon name="cash-minus" size={20} color={mobileTheme.color.action.primary} /><AppText weight={700}>{t('detail.wageDeduction')}</AppText></View><AppText style={styles.negative} weight={700}>{formatInr(Number(item.deductionAmount), language)}</AppText></View><AppText style={styles.muted}>{formatDate(item.deductedAt, language, { dateStyle: 'medium', timeStyle: 'short', timeZone: 'Asia/Kolkata' })}</AppText></Card>) : <EmptyState title={t('detail.noDeductions')} description={t('detail.noDeductionsDescription')} />}</View>
    </>}
    {adjustOpen && detail && organizationId && projectId && accessToken ? <KharchiAdjustmentSheet visible organizationId={organizationId} projectId={projectId} accessToken={accessToken} detail={detail} onClose={() => setAdjustOpen(false)} onSaved={setDetail} /> : null}
  </NirmanScreenBackground>;
}
function Amount({ label, value, emphasis = false }: { label: string; value: string; emphasis?: boolean }) { return <View accessible accessibilityLabel={`${label}: ${value}`} style={styles.amountRow}><AppText style={styles.amountLabel}>{label}</AppText><AppText style={[styles.amountValue, emphasis && styles.emphasis]} weight={700}>{value}</AppText></View>; }
function DetailLine({ label, value }: { label: string; value: string }) { return <View style={styles.detailLine}><AppText style={styles.muted} weight={600}>{label}</AppText><AppText style={styles.detailValue}>{value}</AppText></View>; }
const styles = StyleSheet.create({ identity: { gap: mobileTheme.spacing[2] }, identityTop: { alignItems: 'flex-start', flexDirection: 'row', gap: mobileTheme.spacing[3], justifyContent: 'space-between' }, identityCopy: { flex: 1, gap: mobileTheme.spacing[1] }, code: { ...mobileText.caption, color: mobileTheme.color.action.primary }, worker: { ...mobileText.sectionTitle }, muted: { ...mobileText.caption, color: mobileTheme.color.text.secondary }, card: { gap: mobileTheme.spacing[3] }, section: { gap: mobileTheme.spacing[3] }, sectionTitle: { ...mobileText.sectionTitle }, amountRow: { alignItems: 'center', flexDirection: 'row', gap: mobileTheme.spacing[3], justifyContent: 'space-between', minHeight: 30 }, amountLabel: { ...mobileText.body, color: mobileTheme.color.text.secondary }, amountValue: { ...mobileText.body, fontVariant: ['tabular-nums'] }, emphasis: { color: mobileTheme.color.action.primary, fontSize: 18 }, detailLine: { gap: mobileTheme.spacing[1] }, detailValue: { ...mobileText.body }, historyCard: { gap: mobileTheme.spacing[2] }, historyTop: { alignItems: 'center', flexDirection: 'row', gap: mobileTheme.spacing[3], justifyContent: 'space-between' }, positive: { color: mobileTheme.color.status.success.foreground, fontVariant: ['tabular-nums'] }, negative: { color: mobileTheme.color.status.danger.foreground, fontVariant: ['tabular-nums'] }, deductionLabel: { alignItems: 'center', flexDirection: 'row', gap: mobileTheme.spacing[2] } });
