import { EXPENSE_CATEGORIES, EXPENSE_PAYMENT_METHODS, type ExpenseCategory, type ExpensePaymentMethod, type SiteExpenseDetail } from '@nirman-app/shared';
import { useEffect, useState } from 'react';
import { StyleSheet, View } from 'react-native';
import { useTranslation } from 'react-i18next';

import { BottomSheet, Button, DateInput, FormError, FormField, Input, SearchableSelect } from '../../components/ui';
import { getLocalizedErrorMessage } from '../../i18n';
import { ApiRequestError } from '../../lib/api';
import { mobileTheme } from '../../theme';
import { mutationKey, today } from './expenses-ui';
import { createExpense, updateExpense } from './services';

type Props = { visible: boolean; organizationId: string; projectId: string; accessToken: string; detail?: SiteExpenseDetail | null; onClose: () => void; onSaved: () => void | Promise<void>; onConflict?: () => void | Promise<void> };
type FieldErrors = Partial<Record<'expenseDate' | 'description' | 'amount', string>>;

export function ExpenseFormSheet({ visible, organizationId, projectId, accessToken, detail, onClose, onSaved, onConflict }: Props) {
  const { t } = useTranslation('expenses'); const { t: tCommon } = useTranslation('common');
  const [expenseDate, setExpenseDate] = useState(today()); const [category, setCategory] = useState<ExpenseCategory>('MISCELLANEOUS'); const [description, setDescription] = useState(''); const [amount, setAmount] = useState(''); const [paymentMethod, setPaymentMethod] = useState<ExpensePaymentMethod | null>(null); const [vendorPayee, setVendorPayee] = useState(''); const [saveAsDraft, setSaveAsDraft] = useState(false); const [key, setKey] = useState(mutationKey('expense')); const [working, setWorking] = useState(false); const [formError, setFormError] = useState(''); const [fieldErrors, setFieldErrors] = useState<FieldErrors>({});
  useEffect(() => { if (!visible) return; setExpenseDate(detail?.expenseDate ?? today()); setCategory(detail?.category ?? 'MISCELLANEOUS'); setDescription(detail?.description ?? ''); setAmount(detail?.amount ?? ''); setPaymentMethod(detail?.paymentMethod ?? null); setVendorPayee(detail?.vendorPayee ?? ''); setSaveAsDraft(false); setKey(mutationKey(detail?.id ?? 'expense')); setWorking(false); setFormError(''); setFieldErrors({}); }, [detail, visible]);

  function validate() { const next: FieldErrors = {}; const numericAmount = Number(amount); if (!expenseDate || expenseDate > today()) next.expenseDate = t('validation.date'); if (description.trim().length < 2) next.description = t('validation.description'); if (!Number.isFinite(numericAmount) || numericAmount <= 0 || !/^\d+(\.\d{1,2})?$/.test(amount)) next.amount = t('validation.amount'); setFieldErrors(next); return Object.keys(next).length === 0; }
  async function save() { if (!validate()) { setFormError(t('validation.form')); return; } setWorking(true); setFormError(''); try { const input = { expenseDate, category, description: description.trim(), amount: Number(amount), paymentMethod, vendorPayee: vendorPayee.trim() || null, idempotencyKey: key }; if (detail) await updateExpense(organizationId, projectId, detail.id, accessToken, { ...input, expectedVersion: detail.version }); else await createExpense(organizationId, projectId, accessToken, { ...input, saveAsDraft }); await onSaved(); onClose(); } catch (error) { setFormError(getLocalizedErrorMessage(error, t('errors.saveFailed'))); if (error instanceof ApiRequestError && error.code === 'EXPENSE_VERSION_CONFLICT') await onConflict?.(); } finally { setWorking(false); } }
  const footer = <View style={styles.footer}><Button style={styles.footerButton} label={tCommon('actions.cancel')} variant="secondary" disabled={working} onPress={onClose} /><Button style={styles.footerButton} label={working ? t('loading.saving') : detail ? t('form.saveChanges') : t('form.save')} disabled={working} onPress={() => void save()} /></View>;
  const selectCopy = (field: string) => ({ accessibilityLabel: field, emptyDescription: t('select.emptyDescription'), emptyTitle: t('select.emptyTitle'), placeholder: t('select.choose', { field }), searchAccessibilityLabel: t('select.searchA11y', { field }), searchPlaceholder: t('select.search', { field }), title: t('select.choose', { field }) });

  return <BottomSheet visible={visible} title={detail ? t('form.editTitle') : t('form.createTitle')} description={t('form.description')} scroll showCloseButton={false} onClose={onClose} footer={footer}><FormError message={formError} /><FormField label={t('fields.date')} required error={fieldErrors.expenseDate}><DateInput allowClear={false} showPickerIndicator accessibilityLabel={t('fields.date')} invalid={Boolean(fieldErrors.expenseDate)} maximumDate={new Date()} value={expenseDate} onChangeText={(value) => { setExpenseDate(value); setFieldErrors((current) => ({ ...current, expenseDate: undefined })); }} /></FormField><FormField label={t('fields.category')} required><SearchableSelect value={category} options={EXPENSE_CATEGORIES.map((value) => ({ value, label: t(`category.${value}`) }))} {...selectCopy(t('fields.category'))} onChange={setCategory} /></FormField><FormField label={t('fields.description')} required error={fieldErrors.description}><Input multiline numberOfLines={4} maxLength={1000} invalid={Boolean(fieldErrors.description)} style={styles.multiline} value={description} onChangeText={(value) => { setDescription(value); setFieldErrors((current) => ({ ...current, description: undefined })); }} /></FormField><FormField label={t('fields.amount')} required error={fieldErrors.amount} helperText={t('form.amountHelper')}><Input keyboardType="decimal-pad" invalid={Boolean(fieldErrors.amount)} value={amount} onChangeText={(value) => { setAmount(value.replace(/[^0-9.]/g, '')); setFieldErrors((current) => ({ ...current, amount: undefined })); }} /></FormField><FormField label={t('fields.paymentMethod')}><SearchableSelect<ExpensePaymentMethod | 'NONE'> value={paymentMethod ?? 'NONE'} options={[{ value: 'NONE', label: t('payment.NONE') }, ...EXPENSE_PAYMENT_METHODS.map((value) => ({ value, label: t(`payment.${value}`) }))]} {...selectCopy(t('fields.paymentMethod'))} onChange={(value) => setPaymentMethod(value === 'NONE' ? null : value)} /></FormField><FormField label={t('fields.vendorPayee')} optional><Input maxLength={160} value={vendorPayee} onChangeText={setVendorPayee} /></FormField>{!detail ? <FormField label={t('fields.recordAs')} required><SearchableSelect<'SUBMIT' | 'DRAFT'> value={saveAsDraft ? 'DRAFT' : 'SUBMIT'} options={[{ value: 'SUBMIT', label: t('form.submitNow') }, { value: 'DRAFT', label: t('form.saveDraft') }]} {...selectCopy(t('fields.recordAs'))} onChange={(value) => setSaveAsDraft(value === 'DRAFT')} /></FormField> : null}</BottomSheet>;
}

const styles = StyleSheet.create({ footer: { flex: 1, flexDirection: 'row', gap: mobileTheme.spacing[3] }, footerButton: { flex: 1 }, multiline: { minHeight: 112, paddingTop: mobileTheme.spacing[3], textAlignVertical: 'top' } });
