import type { MaterialRequestDetail } from '@nirman-app/shared';
import { router, useLocalSearchParams } from 'expo-router';
import { useCallback, useEffect, useState } from 'react';
import { Alert, StyleSheet, View } from 'react-native';
import { useTranslation } from 'react-i18next';

import { ActionListItem, AppIcon, AppText, BottomSheet, Button, Card, CompactScreenHeader, DateInput, EmptyState, FormError, FormField, IconButton, Input, LoadingState, NirmanScreenBackground, StatusBadge } from '../../components/ui';
import { formatDate, formatInr, formatNumber, getLocalizedErrorMessage } from '../../i18n';
import { ApiRequestError } from '../../lib/api';
import { getActiveProject, getActiveProjectPermissions } from '../../lib/auth';
import { useLocalization, useSession } from '../../providers';
import { mobileText, mobileTheme } from '../../theme';
import { CustomerTabBar } from '../home/components';
import { ProjectContextCard } from '../projects';
import { MaterialRequestSheet } from './material-request-sheet';
import { MaterialDetailRows, materialTone, mutationKey, today } from './materials-ui';
import { fetchMaterialDetail, recordMaterialDelivery, recordMaterialPurchase, runMaterialCommand } from './services';
import type { MaterialAction } from './types';

const dateValue = (value: string) => new Date(`${value}T12:00:00`);
const dateTime = (value: string) => new Date(value);
const actions: MaterialAction[] = ['EDIT', 'SUBMIT', 'VERIFY', 'APPROVE', 'RETURN', 'REJECT', 'RECORD_PURCHASE', 'RECORD_DELIVERY', 'CANCEL'];

export function MaterialDetailScreen() {
  const { materialRequestId } = useLocalSearchParams<{ materialRequestId?: string }>();
  const { t } = useTranslation('materials'); const { t: tCommon } = useTranslation('common'); const { language } = useLocalization(); const { session } = useSession();
  const project = getActiveProject(session); const permissions = getActiveProjectPermissions(session); const organizationId = session?.activeOrganization?.id; const projectId = project?.id; const token = session?.accessToken;
  const [detail, setDetail] = useState<MaterialRequestDetail | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [editOpen, setEditOpen] = useState(false); const [action, setAction] = useState<MaterialAction | null>(null);

  const load = useCallback(async () => {
    if (!materialRequestId || !organizationId || !projectId || !token) { setLoading(false); return; }
    setLoading(true); setError(''); try { setDetail(await fetchMaterialDetail(organizationId, projectId, materialRequestId, token)); }
    catch (loadError) { setError(getLocalizedErrorMessage(loadError, t('errors.detailFailed'))); } finally { setLoading(false); }
  }, [materialRequestId, organizationId, projectId, t, token]);
  useEffect(() => { void load(); }, [load]);

  function success(next: MaterialRequestDetail, completedAction: Exclude<MaterialAction, 'EDIT'>) { setDetail(next); setAction(null); Alert.alert(t('success.title'), t(`success.${completedAction}`)); }

  return <NirmanScreenBackground footer={<CustomerTabBar activeKey="materials" />}>
    <CompactScreenHeader leading={<IconButton accessibilityLabel={tCommon('actions.back')} icon="arrow-left" variant="glass" onPress={() => router.back()} />} title={t('detail.title')} subtitle={detail?.materialName ?? project?.name} action={detail?.availableActions.includes('EDIT') ? <Button label={t('action.EDIT')} fullWidth={false} size="sm" variant="secondary" leadingIcon="pencil-outline" onPress={() => setEditOpen(true)} /> : undefined} />
    <ProjectContextCard compact />
    {loading ? <LoadingState label={t('loading.detail')} /> : error ? <EmptyState title={t('errors.title')} description={error} actionLabel={tCommon('actions.retry')} onAction={() => void load()} /> : !detail ? <EmptyState title={t('detail.notFound')} description={t('detail.notFoundDescription')} /> : <>
      <Card style={styles.hero}><View style={styles.heroTop}><View style={styles.heroCopy}><AppText style={styles.eyebrow} weight={700}>{detail.category || t('list.uncategorized')}</AppText><AppText style={styles.title} weight={700}>{detail.materialName}</AppText></View><StatusBadge label={t(`status.${detail.status}`)} tone={materialTone(detail.status)} /></View><View style={styles.quantityHero}><View><AppText style={styles.quantity} weight={700}>{formatNumber(Number(detail.deliveredQuantity), language)} / {formatNumber(Number(detail.requestedQuantity), language)}</AppText><AppText style={styles.caption}>{t('detail.deliveredOfRequested', { unit: t(`unit.${detail.unitOfMeasure}`) })}</AppText></View><AppIcon name="package-variant-closed" size={32} color={mobileTheme.color.action.primary} /></View></Card>
      <Card style={styles.sectionCard}><SectionTitle title={t('detail.request')} /><MaterialDetailRows rows={[
        { label: t('fields.requestedBy'), value: detail.requestedBy }, { label: t('fields.requestedOn'), value: formatDate(dateValue(detail.requestedOn), language) }, { label: t('fields.requiredByDate'), value: detail.requiredByDate ? formatDate(dateValue(detail.requiredByDate), language) : t('common.notProvided') }, { label: t('fields.workflow'), value: t(`workflow.${detail.workflowMode}.label`) }, { label: t('fields.estimatedCost'), value: detail.estimatedCost ? formatInr(Number(detail.estimatedCost), language) : t('common.notProvided') }, { label: t('fields.version'), value: formatNumber(detail.version, language) },
      ]} />{detail.notes ? <View style={styles.notes}><AppText style={styles.caption} weight={700}>{t('fields.notes')}</AppText><AppText style={styles.body}>{detail.notes}</AppText></View> : null}</Card>
      <Card style={styles.sectionCard}><SectionTitle title={t('detail.fulfilment')} /><MaterialDetailRows rows={[{ label: t('detail.ordered'), value: `${formatNumber(Number(detail.orderedQuantity), language)} ${t(`unit.${detail.unitOfMeasure}`)}` }, { label: t('detail.delivered'), value: `${formatNumber(Number(detail.deliveredQuantity), language)} ${t(`unit.${detail.unitOfMeasure}`)}` }, { label: t('detail.remaining'), value: `${formatNumber(Number(detail.remainingQuantity), language)} ${t(`unit.${detail.unitOfMeasure}`)}` }, { label: t('detail.purchaseCost'), value: formatInr(Number(detail.totalPurchaseCost), language) }]} /></Card>
      {detail.availableActions.length ? <View style={styles.section}><SectionTitle title={t('detail.availableActions')} />{actions.filter((value) => value !== 'EDIT' && detail.availableActions.includes(value)).map((value) => <ActionListItem key={value} accessibilityLabel={t('actionA11y', { action: t(`action.${value}`), material: detail.materialName })} icon={actionIcon(value)} label={t(`action.${value}`)} tone={value === 'REJECT' || value === 'CANCEL' ? 'danger' : value === 'APPROVE' || value === 'VERIFY' ? 'brand' : 'primary'} onPress={() => setAction(value)} />)}</View> : null}
      <View style={styles.section}><SectionTitle title={t('detail.purchases')} count={detail.purchases.length} />{detail.purchases.length ? detail.purchases.map((purchase) => <Card key={purchase.id} style={styles.historyCard}><View style={styles.historyTop}><AppText weight={700}>{purchase.vendorName || t('purchase.vendorUnknown')}</AppText><AppText style={styles.numeric} weight={700}>{formatNumber(Number(purchase.orderedQuantity), language)} {t(`unit.${detail.unitOfMeasure}`)}</AppText></View><MaterialDetailRows rows={[{ label: t('fields.purchasedOn'), value: formatDate(dateValue(purchase.purchasedOn), language) }, { label: t('fields.orderReference'), value: purchase.orderReference || t('common.notProvided') }, { label: t('fields.totalCost'), value: purchase.totalCost ? formatInr(Number(purchase.totalCost), language) : t('common.notProvided') }, { label: t('fields.recordedBy'), value: purchase.recordedBy }]} />{purchase.notes ? <AppText style={styles.body}>{purchase.notes}</AppText> : null}</Card>) : <AppText style={styles.emptyText}>{t('detail.noPurchases')}</AppText>}</View>
      <View style={styles.section}><SectionTitle title={t('detail.deliveries')} count={detail.deliveries.length} />{detail.deliveries.length ? detail.deliveries.map((delivery) => <Card key={delivery.id} style={styles.historyCard}><View style={styles.historyTop}><AppText weight={700}>{formatDate(dateValue(delivery.deliveredOn), language)}</AppText><AppText style={styles.numeric} weight={700}>{formatNumber(Number(delivery.deliveredQuantity), language)} {t(`unit.${detail.unitOfMeasure}`)}</AppText></View><MaterialDetailRows rows={[{ label: t('fields.deliveryReference'), value: delivery.deliveryReference || t('common.notProvided') }, { label: t('fields.recordedBy'), value: delivery.recordedBy }]} />{delivery.notes ? <AppText style={styles.body}>{delivery.notes}</AppText> : null}</Card>) : <AppText style={styles.emptyText}>{t('detail.noDeliveries')}</AppText>}</View>
      <View style={styles.section}><SectionTitle title={t('detail.timeline')} count={detail.events.length} />{detail.events.map((event, index) => <View key={event.id} style={styles.timelineRow}><View style={styles.timelineRail}><View style={styles.timelineDot} />{index < detail.events.length - 1 ? <View style={styles.timelineLine} /> : null}</View><Card style={styles.eventCard}><View style={styles.historyTop}><AppText weight={700}>{t(`event.${event.eventType}`)}</AppText><AppText style={styles.caption}>{formatDate(dateTime(event.createdAt), language, { dateStyle: 'medium', timeStyle: 'short', timeZone: 'Asia/Kolkata' })}</AppText></View><AppText style={styles.caption}>{event.actorName}</AppText>{event.comment ? <AppText style={styles.body}>{event.comment}</AppText> : null}</Card></View>)}</View>
    </>}
    {editOpen && detail && organizationId && projectId && token ? <MaterialRequestSheet visible organizationId={organizationId} projectId={projectId} accessToken={token} canReadProjectMembers={permissions.includes('project-members:read')} detail={detail} onClose={() => setEditOpen(false)} onSaved={load} onConflict={load} /> : null}
    {action && detail && organizationId && projectId && token ? action === 'RECORD_PURCHASE' ? <PurchaseSheet detail={detail} organizationId={organizationId} projectId={projectId} accessToken={token} onClose={() => setAction(null)} onSaved={(next) => success(next, action)} onConflict={load} /> : action === 'RECORD_DELIVERY' ? <DeliverySheet detail={detail} organizationId={organizationId} projectId={projectId} accessToken={token} onClose={() => setAction(null)} onSaved={(next) => success(next, action)} onConflict={load} /> : action === 'EDIT' ? null : <CommandSheet action={action} detail={detail} organizationId={organizationId} projectId={projectId} accessToken={token} onClose={() => setAction(null)} onSaved={(next) => success(next, action)} onConflict={load} /> : null}
  </NirmanScreenBackground>;
}

function CommandSheet({ action, detail, organizationId, projectId, accessToken, onClose, onSaved, onConflict }: SheetBase & { action: Exclude<MaterialAction, 'EDIT' | 'RECORD_PURCHASE' | 'RECORD_DELIVERY'>; onConflict: () => Promise<void> }) {
  const { t } = useTranslation('materials'); const { t: tCommon } = useTranslation('common'); const [comment, setComment] = useState(''); const [key] = useState(mutationKey(`${detail.id}-${action}`)); const [working, setWorking] = useState(false); const [error, setError] = useState('');
  const required = action === 'RETURN' || action === 'REJECT' || action === 'CANCEL';
  async function submit() { if (required && !comment.trim()) { setError(t('validation.commentRequired')); return; } setWorking(true); setError(''); try { const route = action.toLowerCase() as 'submit' | 'verify' | 'return' | 'approve' | 'reject' | 'cancel'; onSaved(await runMaterialCommand(organizationId, projectId, detail.id, route, accessToken, { expectedVersion: detail.version, comment: comment.trim() || null, idempotencyKey: key })); } catch (commandError) { setError(getLocalizedErrorMessage(commandError, t('errors.actionFailed'))); if (commandError instanceof ApiRequestError && commandError.code === 'MATERIAL_VERSION_CONFLICT') await onConflict(); } finally { setWorking(false); } }
  return <BottomSheet visible title={t(`confirm.${action}.title`)} description={t(`confirm.${action}.description`)} scroll showCloseButton={false} onClose={onClose} footer={<SheetFooter cancel={tCommon('actions.cancel')} save={working ? t('loading.working') : t(`action.${action}`)} working={working} danger={action === 'REJECT' || action === 'CANCEL'} onCancel={onClose} onSave={() => void submit()} />}><FormError message={error} /><FormField label={t('fields.comment')} required={required} optional={!required}><Input multiline numberOfLines={4} maxLength={2000} style={styles.multiline} value={comment} onChangeText={setComment} /></FormField></BottomSheet>;
}

function PurchaseSheet({ detail, organizationId, projectId, accessToken, onClose, onSaved, onConflict }: SheetBase) {
  const { t } = useTranslation('materials'); const { t: tCommon } = useTranslation('common'); const { language } = useLocalization(); const [quantity, setQuantity] = useState(''); const [vendor, setVendor] = useState(''); const [reference, setReference] = useState(''); const [unitCost, setUnitCost] = useState(''); const [totalCost, setTotalCost] = useState(''); const [date, setDate] = useState(today()); const [notes, setNotes] = useState(''); const [key] = useState(mutationKey(`${detail.id}-purchase`)); const [working, setWorking] = useState(false); const [error, setError] = useState('');
  async function save() { const amount = Number(quantity); if (!Number.isFinite(amount) || amount <= 0) { setError(t('validation.quantity')); return; } setWorking(true); setError(''); try { onSaved(await recordMaterialPurchase(organizationId, projectId, detail.id, accessToken, { expectedVersion: detail.version, idempotencyKey: key, orderedQuantity: amount, vendorName: vendor.trim() || null, orderReference: reference.trim() || null, unitCost: unitCost ? Number(unitCost) : null, totalCost: totalCost ? Number(totalCost) : null, purchasedOn: date, notes: notes.trim() || null })); } catch (saveError) { setError(getLocalizedErrorMessage(saveError, t('errors.purchaseFailed'))); if (saveError instanceof ApiRequestError && saveError.code === 'MATERIAL_VERSION_CONFLICT') await onConflict?.(); } finally { setWorking(false); } }
  return <BottomSheet visible title={t('purchase.title')} description={t('purchase.description')} scroll showCloseButton={false} onClose={onClose} footer={<SheetFooter cancel={tCommon('actions.cancel')} save={working ? t('loading.working') : t('purchase.save')} working={working} onCancel={onClose} onSave={() => void save()} />}><FormError message={error} /><FormField label={t('fields.orderedQuantity')} required helperText={t('purchase.requestedHelper', { quantity: formatNumber(Number(detail.requestedQuantity), language), unit: t(`unit.${detail.unitOfMeasure}`) })}><Input keyboardType="decimal-pad" value={quantity} onChangeText={(value) => setQuantity(value.replace(/[^0-9.]/g, ''))} /></FormField><FormField label={t('fields.vendorName')} optional><Input maxLength={160} value={vendor} onChangeText={setVendor} /></FormField><FormField label={t('fields.orderReference')} optional><Input maxLength={120} value={reference} onChangeText={setReference} /></FormField><View style={styles.fieldRow}><FormField style={styles.fieldColumn} label={t('fields.unitCost')} optional><Input keyboardType="decimal-pad" value={unitCost} onChangeText={(value) => setUnitCost(value.replace(/[^0-9.]/g, ''))} /></FormField><FormField style={styles.fieldColumn} label={t('fields.totalCost')} optional><Input keyboardType="decimal-pad" value={totalCost} onChangeText={(value) => setTotalCost(value.replace(/[^0-9.]/g, ''))} /></FormField></View><FormField label={t('fields.purchasedOn')} required><DateInput allowClear={false} accessibilityLabel={t('fields.purchasedOn')} value={date} onChangeText={setDate} /></FormField><FormField label={t('fields.notes')} optional><Input multiline numberOfLines={4} style={styles.multiline} value={notes} onChangeText={setNotes} /></FormField></BottomSheet>;
}

function DeliverySheet({ detail, organizationId, projectId, accessToken, onClose, onSaved, onConflict }: SheetBase) {
  const { t } = useTranslation('materials'); const { t: tCommon } = useTranslation('common'); const { language } = useLocalization(); const [quantity, setQuantity] = useState(''); const [purchaseId, setPurchaseId] = useState<string | null>(null); const [date, setDate] = useState(today()); const [reference, setReference] = useState(''); const [notes, setNotes] = useState(''); const [key] = useState(mutationKey(`${detail.id}-delivery`)); const [working, setWorking] = useState(false); const [error, setError] = useState('');
  async function save() { const amount = Number(quantity); if (!Number.isFinite(amount) || amount <= 0) { setError(t('validation.quantity')); return; } setWorking(true); setError(''); try { onSaved(await recordMaterialDelivery(organizationId, projectId, detail.id, accessToken, { expectedVersion: detail.version, idempotencyKey: key, materialPurchaseId: purchaseId, deliveredQuantity: amount, deliveredOn: date, deliveryReference: reference.trim() || null, notes: notes.trim() || null })); } catch (saveError) { setError(getLocalizedErrorMessage(saveError, t('errors.deliveryFailed'))); if (saveError instanceof ApiRequestError && saveError.code === 'MATERIAL_VERSION_CONFLICT') await onConflict?.(); } finally { setWorking(false); } }
  return <BottomSheet visible title={t('delivery.title')} description={t('delivery.description')} scroll showCloseButton={false} onClose={onClose} footer={<SheetFooter cancel={tCommon('actions.cancel')} save={working ? t('loading.working') : t('delivery.save')} working={working} onCancel={onClose} onSave={() => void save()} />}><FormError message={error} /><FormField label={t('fields.deliveredQuantity')} required helperText={t('delivery.orderedHelper', { quantity: formatNumber(Number(detail.orderedQuantity), language), unit: t(`unit.${detail.unitOfMeasure}`) })}><Input keyboardType="decimal-pad" value={quantity} onChangeText={(value) => setQuantity(value.replace(/[^0-9.]/g, ''))} /></FormField>{detail.purchases.length > 1 ? <FormField label={t('fields.purchase')} optional><View style={styles.choices}><ActionListItem label={t('delivery.anyPurchase')} icon="package-variant" tone={!purchaseId ? 'primary' : 'neutral'} onPress={() => setPurchaseId(null)} />{detail.purchases.map((purchase) => <ActionListItem key={purchase.id} label={`${purchase.vendorName || t('purchase.vendorUnknown')} · ${formatDate(dateValue(purchase.purchasedOn), language)}`} icon="package-variant-closed" tone={purchaseId === purchase.id ? 'primary' : 'neutral'} onPress={() => setPurchaseId(purchase.id)} />)}</View></FormField> : null}<FormField label={t('fields.deliveredOn')} required><DateInput allowClear={false} accessibilityLabel={t('fields.deliveredOn')} value={date} onChangeText={setDate} /></FormField><FormField label={t('fields.deliveryReference')} optional><Input maxLength={120} value={reference} onChangeText={setReference} /></FormField><FormField label={t('fields.notes')} optional><Input multiline numberOfLines={4} style={styles.multiline} value={notes} onChangeText={setNotes} /></FormField></BottomSheet>;
}

type SheetBase = { detail: MaterialRequestDetail; organizationId: string; projectId: string; accessToken: string; onClose: () => void; onSaved: (detail: MaterialRequestDetail) => void; onConflict?: () => void | Promise<void> };
function SheetFooter({ cancel, save, working, danger = false, onCancel, onSave }: { cancel: string; save: string; working: boolean; danger?: boolean; onCancel: () => void; onSave: () => void }) { return <View style={styles.sheetFooter}><Button style={styles.footerButton} label={cancel} variant="secondary" disabled={working} onPress={onCancel} /><Button style={styles.footerButton} label={save} variant={danger ? 'danger' : 'primary'} disabled={working} onPress={onSave} /></View>; }
function SectionTitle({ title, count }: { title: string; count?: number }) { return <View style={styles.sectionTitleRow}><AppText style={styles.sectionTitle} weight={700}>{title}</AppText>{count !== undefined ? <AppText style={styles.count} weight={700}>{count}</AppText> : null}</View>; }
function actionIcon(action: MaterialAction) { const map: Record<MaterialAction, Parameters<typeof AppIcon>[0]['name']> = { EDIT: 'pencil-outline', SUBMIT: 'send-outline', VERIFY: 'check-decagram-outline', APPROVE: 'check-circle-outline', RETURN: 'undo-variant', REJECT: 'close-circle-outline', CANCEL: 'cancel', RECORD_PURCHASE: 'cart-outline', RECORD_DELIVERY: 'truck-delivery-outline' }; return map[action]; }

const styles = StyleSheet.create({
  hero: { gap: mobileTheme.spacing[4] }, heroTop: { alignItems: 'flex-start', flexDirection: 'row', gap: mobileTheme.spacing[3], justifyContent: 'space-between' }, heroCopy: { flex: 1, gap: mobileTheme.spacing[1] }, eyebrow: { ...mobileText.caption, color: mobileTheme.color.action.primary }, title: { ...mobileText.title, fontSize: 24, lineHeight: 30 }, quantityHero: { alignItems: 'center', backgroundColor: mobileTheme.color.brand.secondarySoft, borderRadius: mobileTheme.radius.lg, flexDirection: 'row', justifyContent: 'space-between', padding: mobileTheme.spacing[4] }, quantity: { ...mobileText.title, color: mobileTheme.color.action.primary, fontVariant: ['tabular-nums'] }, caption: { ...mobileText.caption }, body: { ...mobileText.body, color: mobileTheme.color.text.primary },
  section: { gap: mobileTheme.spacing[3] }, sectionCard: { gap: mobileTheme.spacing[3] }, sectionTitleRow: { alignItems: 'center', flexDirection: 'row', gap: mobileTheme.spacing[2], justifyContent: 'space-between' }, sectionTitle: { ...mobileText.sectionTitle }, count: { ...mobileText.caption, backgroundColor: mobileTheme.color.status.info.background, borderRadius: mobileTheme.radius.full, color: mobileTheme.color.status.info.foreground, minWidth: 28, overflow: 'hidden', paddingHorizontal: mobileTheme.spacing[2], paddingVertical: mobileTheme.spacing[1], textAlign: 'center' }, notes: { borderTopColor: mobileTheme.color.border.subtle, borderTopWidth: 1, gap: mobileTheme.spacing[2], paddingTop: mobileTheme.spacing[3] },
  historyCard: { gap: mobileTheme.spacing[3] }, historyTop: { alignItems: 'flex-start', flexDirection: 'row', gap: mobileTheme.spacing[3], justifyContent: 'space-between' }, numeric: { ...mobileText.body, color: mobileTheme.color.action.primary, fontVariant: ['tabular-nums'], textAlign: 'right' }, emptyText: { ...mobileText.body, color: mobileTheme.color.text.muted },
  timelineRow: { alignItems: 'stretch', flexDirection: 'row', gap: mobileTheme.spacing[3] }, timelineRail: { alignItems: 'center', width: 18 }, timelineDot: { backgroundColor: mobileTheme.color.action.primary, borderColor: mobileTheme.color.surface.raised, borderRadius: 6, borderWidth: 2, height: 12, marginTop: mobileTheme.spacing[4], width: 12 }, timelineLine: { backgroundColor: mobileTheme.color.border.accent, flex: 1, width: 2 }, eventCard: { flex: 1, gap: mobileTheme.spacing[2], marginBottom: mobileTheme.spacing[2] },
  multiline: { minHeight: 104, paddingTop: mobileTheme.spacing[3], textAlignVertical: 'top' }, sheetFooter: { flex: 1, flexDirection: 'row', gap: mobileTheme.spacing[3] }, footerButton: { flex: 1 }, fieldRow: { flexDirection: 'row', flexWrap: 'wrap', gap: mobileTheme.spacing[3] }, fieldColumn: { flex: 1, minWidth: 140 }, choices: { gap: mobileTheme.spacing[2] },
});
